version: "3.8"
services:
    app:
        build: 
            args: 
                user: thiel-serra
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        container_name: lrv-web-service_app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks: 
            - laravel-web-service
    
    nginx:
        image: nginx:alpine
        container_name: lrv-web-service_nginx
        restart: unless-stopped
        ports: 
            - 8020:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel-web-service

    mysql:
        image: mysql:5.7.22
        container_name: lrv-web-service_mysql
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - 3320:3306
        networks: 
            - laravel-web-service

networks: 
    laravel-web-service:
        driver: bridge